from pathlib import Path

from django.conf import settings

DEFAULT_PAGE_SIZE = 6
PAGE_SIZE_QUERY_PARAM = 'limit'
NAME_MAX_LENGTH = 256
TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32
INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 64
MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 32767
MIN_INGREDIENT_AMOUNT = 1
MAX_INGREDIENT_AMOUNT = 32767
RECIPE_NAME_MAX_LENGTH = 25
INGREDIENTS_PATH = Path(settings.BASE_DIR) / 'data' / 'ingredients.json'
